### ISSUE TITLE
last-dotplot was killed with large alignment output

### ISSUE THREAD

**Issue by chengbing0404** [UCSantaCruzComputationalGenomicsLab/last#2]
Hi there, 

I had run last-dotplot with last output based on two genome assemblies (~700MB each). Since the output is 380G, the software had a problem reading the alignment and was killed in the end. I tried those scripts to filter in chromosome level but it was failed. I also tried to use more stringent parameter and gave another run, however, the output is still very big (210G) and again the job was killed.

Can you please advise how to generate a dot plot **at a genome level** **with a large LAST alignment output**?  Thanks!

Kind regards,

BC

**Comment by diekhans** [comment]
This is only a copy of last software for our own use.  We are unable to provide help  Please visit the last home page:  http://last.cbrc.jp/
